---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Do-to"
host: ""
basePath: "/api"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /goals/{section}:
    get:
      tags:
        - "Goal"
      summary: "goal by single section selected"
      description: ""
      operationId: "goals-section"
      produces:
        - "application/json"
      parameters:
        - name: "section"
          in: "path"
          required: true
          x-exportParamName: "Section"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Goal"
  /goals?section:
    get:
      tags:
        - "Goal"
      summary: "multiple goals by section"
      description: ""
      operationId: "goals-section-query"
      produces:
        - "application/json"
      parameters:
        - name: "section"
          in: "query"
          required: true
          collectionFormat: "csv"
          x-exportParamName: "Section"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Goal"
  /goal/{section}:
    post:
      tags:
        - "Goal"
      summary: "post goal"
      description: "Adds goal"
      operationId: "goal-post"
      produces:
        - "application/json"
      parameters:
        - name: "section"
          in: "path"
          required: true
          x-exportParamName: "Section"
        - in: "body"
          name: "content"
          required: true
          schema:
            $ref: "#/definitions/Goal"
          x-exportParamName: "Content"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Goal"
definitions:
  Goal:
    properties:
      name:
        type: "string"
      description:
        type: "string"
      id:
        type: "integer"
        format: "int64"
      timestamp:
        type: "string"
      section:
        $ref: "#/definitions/Goal_sections"
      tasks:
        $ref: "#/definitions/Task"
    example:
      name: "name"
      description: "description"
      section: {}
      id: 0
      tasks:
        estimation: "estimation"
        name: "name"
        description: "description"
        section: null
        id: 6
        subtask: null
        timestamp: "timestamp"
      timestamp: "timestamp"
  Task:
    properties:
      id:
        type: "integer"
        format: "int64"
      section:
        $ref: "#/definitions/Goal_sections"
      name:
        type: "string"
      description:
        type: "string"
      timestamp:
        type: "string"
        format: "full-date"
      estimation:
        type: "string"
        format: "full-date"
      subtask:
        $ref: "#/definitions/Task"
    example:
      estimation: "estimation"
      name: "name"
      description: "description"
      section: null
      id: 6
      subtask: null
      timestamp: "timestamp"
  Goal_sections:
    type: "string"
    enum:
      - "productivity"
      - "todo"
      - "enhancement"
      - "proficiency"
