/*
 * Do-to
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Goal_sections string

// List of Goal_sections
const (
	PRODUCTIVITY Goal_sections = "productivity"
	TODO Goal_sections = "todo"
	ENHANCEMENT Goal_sections = "enhancement"
	PROFICIENCY Goal_sections = "proficiency"
)
