// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Do-to

    Schemes:
      http
    Host: localhost:3000
    BasePath: /api
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
