/**
 * Do-to
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GoalSections } from './goalSections';


export interface Task { 
    id?: number;
    section?: GoalSections;
    name?: string;
    description?: string;
    timestamp?: string;
    estimation?: string;
    subtask?: Task;
}
