// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TaskPostHandlerFunc turns a function with the right signature into a task post handler
type TaskPostHandlerFunc func(TaskPostParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TaskPostHandlerFunc) Handle(params TaskPostParams) middleware.Responder {
	return fn(params)
}

// TaskPostHandler interface for that can handle valid task post params
type TaskPostHandler interface {
	Handle(TaskPostParams) middleware.Responder
}

// NewTaskPost creates a new http.Handler for the task post operation
func NewTaskPost(ctx *middleware.Context, handler TaskPostHandler) *TaskPost {
	return &TaskPost{Context: ctx, Handler: handler}
}

/*TaskPost swagger:route POST /task Task taskPost

post task

Adds task

*/
type TaskPost struct {
	Context *middleware.Context
	Handler TaskPostHandler
}

func (o *TaskPost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTaskPostParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
