// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/rusakov/doto/server/api/models"
)

// TaskPostOKCode is the HTTP code returned for type TaskPostOK
const TaskPostOKCode int = 200

/*TaskPostOK Successful operation

swagger:response taskPostOK
*/
type TaskPostOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Task `json:"body,omitempty"`
}

// NewTaskPostOK creates TaskPostOK with default headers values
func NewTaskPostOK() *TaskPostOK {

	return &TaskPostOK{}
}

// WithPayload adds the payload to the task post o k response
func (o *TaskPostOK) WithPayload(payload []*models.Task) *TaskPostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the task post o k response
func (o *TaskPostOK) SetPayload(payload []*models.Task) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TaskPostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Task, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
