// Code generated by go-swagger; DO NOT EDIT.

package goal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// GoalsSectionQueryURL generates an URL for the goals section query operation
type GoalsSectionQueryURL struct {
	Sections []string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GoalsSectionQueryURL) WithBasePath(bp string) *GoalsSectionQueryURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GoalsSectionQueryURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GoalsSectionQueryURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/goals"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var sectionsIR []string
	for _, sectionsI := range o.Sections {
		sectionsIS := sectionsI
		if sectionsIS != "" {
			sectionsIR = append(sectionsIR, sectionsIS)
		}
	}

	sections := swag.JoinByFormat(sectionsIR, "csv")

	if len(sections) > 0 {
		qsv := sections[0]
		if qsv != "" {
			qs.Set("sections", qsv)
		}
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GoalsSectionQueryURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GoalsSectionQueryURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GoalsSectionQueryURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GoalsSectionQueryURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GoalsSectionQueryURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GoalsSectionQueryURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
