// Code generated by go-swagger; DO NOT EDIT.

package goal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GoalsSectionQueryHandlerFunc turns a function with the right signature into a goals section query handler
type GoalsSectionQueryHandlerFunc func(GoalsSectionQueryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GoalsSectionQueryHandlerFunc) Handle(params GoalsSectionQueryParams) middleware.Responder {
	return fn(params)
}

// GoalsSectionQueryHandler interface for that can handle valid goals section query params
type GoalsSectionQueryHandler interface {
	Handle(GoalsSectionQueryParams) middleware.Responder
}

// NewGoalsSectionQuery creates a new http.Handler for the goals section query operation
func NewGoalsSectionQuery(ctx *middleware.Context, handler GoalsSectionQueryHandler) *GoalsSectionQuery {
	return &GoalsSectionQuery{Context: ctx, Handler: handler}
}

/*GoalsSectionQuery swagger:route GET /goals Goal goalsSectionQuery

multiple goals by section

*/
type GoalsSectionQuery struct {
	Context *middleware.Context
	Handler GoalsSectionQueryHandler
}

func (o *GoalsSectionQuery) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGoalsSectionQueryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
