// Code generated by go-swagger; DO NOT EDIT.

package goal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/rusakov/doto/server/api/models"
)

// NewGoalPostParams creates a new GoalPostParams object
// no default values defined in spec.
func NewGoalPostParams() GoalPostParams {

	return GoalPostParams{}
}

// GoalPostParams contains all the bound params for the goal post operation
// typically these are obtained from a http.Request
//
// swagger:parameters goal-post
type GoalPostParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Content *models.Goal
	/*
	  Required: true
	  In: path
	*/
	Section []string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGoalPostParams() beforehand.
func (o *GoalPostParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Goal
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("content", "body"))
			} else {
				res = append(res, errors.NewParseError("content", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Content = &body
			}
		}
	} else {
		res = append(res, errors.Required("content", "body"))
	}
	rSection, rhkSection, _ := route.Params.GetOK("section")
	if err := o.bindSection(rSection, rhkSection, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSection binds and validates array parameter Section from path.
//
// Arrays are parsed according to CollectionFormat: "" (defaults to "csv" when empty).
func (o *GoalPostParams) bindSection(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("section", "path")
	}

	var qvSection string
	if len(rawData) > 0 {
		qvSection = rawData[len(rawData)-1]
	}

	// CollectionFormat:
	sectionIC := swag.SplitByFormat(qvSection, "")

	if len(sectionIC) == 0 {
		return errors.Required("section", "path")
	}

	var sectionIR []string
	for i, sectionIV := range sectionIC {
		sectionI := sectionIV

		if err := validate.Enum(fmt.Sprintf("%s.%v", "section", i), "path", sectionI, []interface{}{"productivity", "todo", "enhancement", "proficiency"}); err != nil {
			return err
		}

		sectionIR = append(sectionIR, sectionI)
	}

	o.Section = sectionIR

	return nil
}
