// Code generated by go-swagger; DO NOT EDIT.

package goal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GoalPostURL generates an URL for the goal post operation
type GoalPostURL struct {
	Section []string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GoalPostURL) WithBasePath(bp string) *GoalPostURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GoalPostURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GoalPostURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/goal/{section}"

	var sectionIR []string
	for _, sectionI := range o.Section {
		sectionIS := sectionI
		if sectionIS != "" {
			sectionIR = append(sectionIR, sectionIS)
		}
	}

	section := swag.JoinByFormat(sectionIR, "")
	if len(section) > 0 {
		psv := section[0]
		if psv != "" {
			_path = strings.Replace(_path, "{section}", psv, -1)
		} else {
			return nil, errors.New("Section is required on SectionURL")
		}
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GoalPostURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GoalPostURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GoalPostURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GoalPostURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GoalPostURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GoalPostURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
