// Code generated by go-swagger; DO NOT EDIT.

package goal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/rusakov/doto/server/api/models"
)

// GoalPostOKCode is the HTTP code returned for type GoalPostOK
const GoalPostOKCode int = 200

/*GoalPostOK Successful operation

swagger:response goalPostOK
*/
type GoalPostOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Goal `json:"body,omitempty"`
}

// NewGoalPostOK creates GoalPostOK with default headers values
func NewGoalPostOK() *GoalPostOK {

	return &GoalPostOK{}
}

// WithPayload adds the payload to the goal post o k response
func (o *GoalPostOK) WithPayload(payload []*models.Goal) *GoalPostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the goal post o k response
func (o *GoalPostOK) SetPayload(payload []*models.Goal) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GoalPostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Goal, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
